from . import product_budget
from . import man_power
from . import fabrication_category
from . import buying
from . import inherit
from . import bom
from . import crm
from . import res_users
from . import purchase_order