{
    'name': 'Hymech Beta',
    'version': '1.0',
    'category': 'CRM',
    'description': "hi",
    'website': 'https://www.odoo.com/page/crm',
    'depends': ['base', 'account', 'sale', 'purchase', 'stock'],
    'author': "Author name(Hymech)",
    'sequence' : 0,
    'data': [
                'security/ir.model.access.csv',
                # 'views/product_budget.xml',
                # 'views/man_power.xml',
                # 'views/fabrication_category.xml',
                # 'views/material.xml',
                # 'views/tools.xml',
                # 'views/equipment.xml',
                # 'views/transport.xml',
                # 'views/buying.xml',
                # 'report/header.xml',
                # 'report/sum.xml',
                # 'report/purchase_order.xml',
                'views/invoice_inherit.xml',
                'views/sale_inherit.xml',
                # 'views/bom.xml',
                'views/delivery_inherit.xml',
                'views/sale_inherit_one.xml',
                'views/invoice_inherit_one.xml',
                'views/delivery_inherit_one.xml',
                'views/crm.xml',
                'report/view.xml',
                'report/delivery.xml',
                'report/quotation.xml',
                'report/invoices_one_pdf_reports.xml',
                'report/custom_invoice_pdf.xml',
                'report/purchase_pdf.xml',
                'views/purchase_inherit_one.xml',
                'views/res_users_views.xml',
                'views/expenses_inherit.xml',
                'views/invoice_inherit.xml',
                # 'views/res_partner_inherit.xml',
    
            ],
    "init_xml": [],
    'update_xml': [],
    'demo_xml': [],
    "qweb": [
        # "static/src/xml/*.xml",
    ],
    'images': ['static/description/icon.jpg','static/description/main_screenshot.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}