{
    'name': 'Hymech product ',
    'version': '1.0',
    'category': 'CRM',
    'description': "hi",
    'website': 'https://www.odoo.com/page/crm',
    'depends': ['base','account','sale','sale_approve', 'stock', 'purchase'],
    'author': "Author name(Hymech)",
    'sequence' : 0,
    'data': [
                'security/ir.model.access.csv',
                'views/product_budget.xml',
                'views/man_power.xml',
                'views/fabrication_category.xml',
                'views/material.xml',
                'views/tools.xml',
                'views/equipment.xml',
                'views/transport.xml',
                # 'views/purchase_order.xml',
                'views/hr_employee.xml',
                # 'views/operator.xml',
                'views/bom.xml',
                'views/process.xml',
                'views/task.xml',
                'views/project.xml',
                'views/expense.xml',
                'report/product_budget_pdf.xml',
                'report/pdf.xml',
                'views/purchase.xml',
                'views/hr_employee_line.xml',
                'data/data.xml',
                'views/vendor_bill.xml',
                'views/pass.xml',
                'views/pass_type.xml',
                'views/vendor_tree.xml',
                'views/vendor_bill_line.xml',
                'views/site.xml',
                'views/design.xml',
                'views/category_design.xml',
                # 'report/quotation.xml',
                # 'report/view.xml',
                'views/attendance.xml',
                'wizard/process_model.xml',
                'views/terms_condition.xml',

                
    
            ],
    "init_xml": [],
    'update_xml': [],
    'demo_xml': [],
    "qweb": [
        # "static/src/xml/*.xml",
    ],
    'images': ['static/description/icon.jpg','static/description/main_screenshot.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}