# -*- coding: utf-8 -*-
{
    'name': 'Inspection',
    'version': '17.0.1.0.0',
    'summary': 'Record Model Information',
    'category': 'Tools',
    'author': 'odoo',
    'maintainer': 'odoo developer',
    'company': 'odoo Model',
    'website': ' ',
    'depends': [
        'base',
        'base_import',
        'contacts',
        'hr',
        'asset',
        'deltatech_property',
        'serviceprovider',
        'newassets',
        'mail',
    ],
    'data': [
        'views/inspection.xml',
        'views/inspectionrequest.xml',
        'views/checklist.xml',
        'views/check_list_item.xml',
        'views/contact.xml',
        'views/inspectionplan.xml',
        'views/inspectorform.xml',
        'views/checkresult.xml',
        'views/checkresulteq.xml',
        'views/checkcategory.xml',
        'views/checklistline.xml',
        'views/dynamic_update.xml',
        # 'views/inspectiortask.xml',
        'data/sequence.xml',
        'data/cron.xml',
        'views/firebase.xml',
        'views/onesignal.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'reports/inspectionreport.xml',
        'reports/inspectionresult.xml',
        'reports/inspectionequip.xml',
        # 'views/emailtemplate.xml',
        # 'views/emailequipment.xml',
       
    ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}

